const dummyData = [
    {
      id: 1,
      type: 'Flat',
      name: 'Sunshine Apartments',
      bhk: 2,
      cost: 12000,
      totalRooms: 3,
      availableRooms: 2,
      rating: 4.5,
      features: ['Parking', 'Security', 'Power Backup'],
      images: ['/assets/property-1.jpg'],
      street: '123 Main Street',
      city: 'Bangalore',
      state: 'Karnataka',
      zipCode: '560001'
    },
    {
      id: 2,
      type: 'PG',
      name: 'Urban Stay',
      cost: 8000,
      totalRooms: 10,
      availableRooms: 4,
      rating: 4.2,
      capacity: 2,
      features: ['WiFi', 'Food', 'Laundry'],
      images: ['/assets/property-1.jpg'],
      street: '456 Park Road',
      city: 'Mumbai',
      state: 'Maharashtra',
      zipCode: '400001'
    },
    {
      id: 3,
      type: 'Hostel',
      name: 'Green Hostel',
      cost: 5000,
      totalRooms: 20,
      availableRooms: 10,
      rating: 3.8,
      capacity: 4,
      features: ['WiFi', '24/7 Security', 'Cafeteria'],
      images: ['/assets/property-2.jpg'],
      street: '789 Green Lane',
      city: 'Chennai',
      state: 'Tamil Nadu',
      zipCode: '600001'
    },
    {
      id: 4,
      type: 'Flat',
      name: 'Ocean View Apartments',
      bhk: 3,
      cost: 18000,
      totalRooms: 4,
      availableRooms: 1,
      rating: 4.7,
      features: ['Swimming Pool', 'Gym', 'Parking'],
      images: ['/assets/property-3.jpg'],
      street: '101 Ocean Drive',
      city: 'Goa',
      state: 'Goa',
      zipCode: '403001'
    },
    {
      id: 5,
      type: 'PG',
      name: 'City PG',
      cost: 7000,
      totalRooms: 15,
      availableRooms: 5,
      rating: 4.0,
      capacity: 3,
      features: ['WiFi', 'Housekeeping', 'Laundry'],
      images: ['/assets/property-2.jpg'],
      street: '202 City Road',
      city: 'Pune',
      state: 'Maharashtra',
      zipCode: '411001'
    }
  ];
  
  export default dummyData;